CREATE TABLE IF NOT EXISTS affiliate_documents (
  id BIGINT(20) UNSIGNED NOT NULL AUTO_INCREMENT,
  agency_id BIGINT(20) UNSIGNED NOT NULL,
  client_id BIGINT(20) UNSIGNED NOT NULL,
  affiliation_id BIGINT(20) UNSIGNED DEFAULT NULL,
  monthly_payment_id BIGINT(20) UNSIGNED DEFAULT NULL,
  uploaded_by_user_id BIGINT(20) UNSIGNED NOT NULL,
  document_type VARCHAR(50) NOT NULL,
  display_name VARCHAR(255) NOT NULL,
  source ENUM('admin', 'office_manager', 'system', 'affiliate') NOT NULL DEFAULT 'office_manager',
  original_name VARCHAR(255) NOT NULL,
  storage_key VARCHAR(500) NOT NULL,
  mime_type VARCHAR(120) NOT NULL,
  size_bytes BIGINT(20) UNSIGNED NOT NULL,
  sha256 CHAR(64) NOT NULL,
  is_visible_to_affiliate TINYINT(1) NOT NULL DEFAULT 1,
  created_at TIMESTAMP(6) NULL DEFAULT CURRENT_TIMESTAMP(6),
  updated_at TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP() ON UPDATE CURRENT_TIMESTAMP(),
  PRIMARY KEY (id),
  UNIQUE KEY uk_affiliate_document_storage_key (storage_key),
  KEY idx_affiliate_documents_client (client_id, created_at),
  KEY idx_affiliate_documents_affiliation (affiliation_id),
  KEY idx_affiliate_documents_payment (monthly_payment_id),
  KEY idx_affiliate_documents_agency (agency_id, client_id),
  CONSTRAINT fk_affiliate_documents_agency FOREIGN KEY (agency_id) REFERENCES agencies (id),
  CONSTRAINT fk_affiliate_documents_client FOREIGN KEY (client_id) REFERENCES clients (id),
  CONSTRAINT fk_affiliate_documents_affiliation FOREIGN KEY (affiliation_id) REFERENCES affiliations (id),
  CONSTRAINT fk_affiliate_documents_payment FOREIGN KEY (monthly_payment_id) REFERENCES monthly_payments (id),
  CONSTRAINT fk_affiliate_documents_uploaded_by FOREIGN KEY (uploaded_by_user_id) REFERENCES users (id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
